// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7awnp8NMC_PoU_phhJxYS-I83ohnQVo0',
    appId: '1:805606598845:web:5f74d5a938013e35cdefd4',
    messagingSenderId: '805606598845',
    projectId: 'todoapp-e418c',
    authDomain: 'todoapp-e418c.firebaseapp.com',
    storageBucket: 'todoapp-e418c.appspot.com',
    measurementId: 'G-MFVN4HFYQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9XBU6cBi1yU6hC2rtAJDkhl8ZxHXY454',
    appId: '1:805606598845:android:5049f18f136ee535cdefd4',
    messagingSenderId: '805606598845',
    projectId: 'todoapp-e418c',
    storageBucket: 'todoapp-e418c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb52KarJJJsVTrX8boXxc_95nrV-4BHWI',
    appId: '1:805606598845:ios:973afd6d526feac4cdefd4',
    messagingSenderId: '805606598845',
    projectId: 'todoapp-e418c',
    storageBucket: 'todoapp-e418c.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );
}
